<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="LIN-5CD5329MYS" failures="1" tests="1" name="fireTest" time="11.072" errors="0" timestamp="2025-10-17T16:00:32 IST">
  <testcase classname="Oct_17.App" name="login" time="3.99">
    <failure type="java.lang.AssertionError" message="expected [bbb] but found [aaa]">
      <![CDATA[java.lang.AssertionError: expected [bbb] but found [aaa]
at Oct_17.App.login(App.java:51)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
at java.base/java.lang.Thread.run(Thread.java:1583)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- login -->
</testsuite> <!-- fireTest -->
